import { NextResponse } from "next/server";
import PDFDocument from "pdfkit";

export async function GET() {
  const pdfBuffer = await generatePdf();

  return new NextResponse(pdfBuffer as BodyInit, {
    status: 200,
    headers: {
      "Content-Type": "application/pdf",
      "Content-Disposition":
        'attachment; filename="ats-ministry-summary.pdf"',
    },
  });
}

function generatePdf(): Promise<Buffer> {
  return new Promise<Buffer>((resolve, reject) => {
    const doc = new PDFDocument();
    const chunks: Buffer[] = [];

    doc.fontSize(18).text("ATS Ministry Dashboard Summary", {
      underline: true,
    });

    doc.moveDown();

    doc
      .fontSize(12)
      .text("Generated by ATS Federation Console.");

    doc.on("data", (chunk: Buffer) => {
      chunks.push(chunk);
    });

    doc.on("end", () => {
      resolve(Buffer.concat(chunks));
    });

    doc.on("error", (error) => {
      reject(error);
    });

    doc.end();
  });
}
