#!/bin/bash

# ============================================================
# ATS BACKEND INTEGRATION MASTER SCRIPT (SUPABASE VERSION)
# ============================================================
# Sends JSON payloads generated by ATS modules into Supabase
# Modules:
#  - onboarding.sh
#  - certificate_activation.sh
#  - tier_selection.sh
#  - property_scaling.sh
#  - allocation_engine.sh
#  - unit_assignment.sh
#  - insurance_scaling.sh
# ============================================================

# -----------------------------
# SUPABASE CONFIG
# -----------------------------
BASE_URL="https://wtifrlhiyzudgppqswzw.supabase.co"

# All ATS data goes into the "members" table for now
API_ONBOARD="/rest/v1/members"
API_CERT="/rest/v1/members"
API_TIER="/rest/v1/members"
API_SCALING="/rest/v1/members"
API_ALLOC="/rest/v1/members"
API_UNIT="/rest/v1/members"
API_INS="/rest/v1/members"

# Supabase keys (anon key used for client-side writes)
AUTH_HEADER="Authorization: Bearer sb_publishable_eLu_k-kp9xTcQcM0hTRIwg_trevTugn"
APIKEY_HEADER="apikey: sb_publishable_eLu_k-kp9xTcQcM0hTRIwg_trevTugn"
CONTENT_HEADER="Content-Type: application/json"

# -----------------------------
# 1. SEND ONBOARDING PAYLOAD
# -----------------------------
send_onboarding() {
  echo "Sending onboarding_payload.json..."
  curl -X POST "$BASE_URL$API_ONBOARD" \
    -H "$AUTH_HEADER" \
    -H "$APIKEY_HEADER" \
    -H "$CONTENT_HEADER" \
    -d @onboarding_payload.json
  echo
}

# -----------------------------
# 2. SEND CERTIFICATE ACTIVATION
# -----------------------------
send_certificate() {
  echo "Sending certificate_payload.json..."
  curl -X POST "$BASE_URL$API_CERT" \
    -H "$AUTH_HEADER" \
    -H "$APIKEY_HEADER" \
    -H "$CONTENT_HEADER" \
    -d @certificate_payload.json
  echo
}

# -----------------------------
# 3. SEND TIER SELECTION
# -----------------------------
send_tier() {
  echo "Sending tier_payload.json..."
  curl -X POST "$BASE_URL$API_TIER" \
    -H "$AUTH_HEADER" \
    -H "$APIKEY_HEADER" \
    -H "$CONTENT_HEADER" \
    -d @tier_payload.json
  echo
}

# -----------------------------
# 4. SEND PROPERTY SCALING
# -----------------------------
send_scaling() {
  echo "Sending scaling_payload.json..."
  curl -X POST "$BASE_URL$API_SCALING" \
    -H "$AUTH_HEADER" \
    -H "$APIKEY_HEADER" \
    -H "$CONTENT_HEADER" \
    -d @scaling_payload.json
  echo
}

# -----------------------------
# 5. SEND ALLOCATION PAYLOAD
# -----------------------------
send_allocation() {
  echo "Sending allocation_payload.json..."
  curl -X POST "$BASE_URL$API_ALLOC" \
    -H "$AUTH_HEADER" \
    -H "$APIKEY_HEADER" \
    -H "$CONTENT_HEADER" \
    -d @allocation_payload.json
  echo
}

# -----------------------------
# 6. SEND UNIT ASSIGNMENT
# -----------------------------
send_unit_assignment() {
  echo "Sending unit_assignment_payload.json..."
  curl -X POST "$BASE_URL$API_UNIT" \
    -H "$AUTH_HEADER" \
    -H "$APIKEY_HEADER" \
    -H "$CONTENT_HEADER" \
    -d @unit_assignment_payload.json
  echo
}

# -----------------------------
# 7. SEND INSURANCE SCALING
# -----------------------------
send_insurance_scaling() {
  echo "Sending insurance_scaling_payload.json..."
  curl -X POST "$BASE_URL$API_INS" \
    -H "$AUTH_HEADER" \
    -H "$APIKEY_HEADER" \
    -H "$CONTENT_HEADER" \
    -d @insurance_scaling_payload.json
  echo
}

# -----------------------------
# MASTER MENU
# -----------------------------
echo "ATS Backend Integration"
echo "1) Send Onboarding"
echo "2) Send Certificate Activation"
echo "3) Send Tier Selection"
echo "4) Send Property Scaling"
echo "5) Send Allocation"
echo "6) Send Unit Assignment"
echo "7) Send Insurance Scaling"
echo "8) Run Full Flow (1→7)"
read -p "Choose option: " choice

case "$choice" in
  1) send_onboarding ;;
  2) send_certificate ;;
  3) send_tier ;;
  4) send_scaling ;;
  5) send_allocation ;;
  6) send_unit_assignment ;;
  7) send_insurance_scaling ;;
  8)
    send_onboarding
    send_certificate
    send_tier
    send_scaling
    send_allocation
    send_unit_assignment
    send_insurance_scaling
    ;;
  *) echo "Invalid choice" ;;
esac
