import { NextResponse } from "next/server";
import PDFDocument from "pdfkit";

export async function GET() {
  const doc = new PDFDocument();
  const chunks: Buffer[] = [];

  doc.fontSize(18).text("ATS Ministry Dashboard Summary", { underline: true });
  doc.moveDown();
  doc.fontSize(12).text("Generated by ATS Federation Console.");

  doc.end();

  return new Promise((resolve) => {
    doc.on("data", (chunk) => chunks.push(chunk));
    doc.on("end", () => {
      const pdfBuffer = Buffer.concat(chunks);
      resolve(
        new NextResponse(pdfBuffer, {
          status: 200,
          headers: {
            "Content-Type": "application/pdf",
            "Content-Disposition":
              'attachment; filename="ats-ministry-summary.pdf"',
          },
        })
      );
    });
  });
}
